package notify

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"io"
	"os/exec"
	"regexp"
	"strings"
	"sync"
	"time"
	"unicode"
	"unicode/utf8"
)

const (
	defaultPiHelperBin       = "steward-pi-helper"
	defaultPiModelProvider   = "openai-codex"
	defaultPiModelID         = "gpt-5.6-luna"
	defaultPiModelThinking   = "low"
	maximumPiSettingBytes    = 256
	maximumPiInputBytes      = 8192
	reservedPiInputBytes     = 4096
	maximumPiLabelBytes      = 120
	maximumPiWireBytes       = 64 * 1024
	maximumPiOutputBytes     = 4096
	maximumPiBodyCodepoints  = 180
	maximumPiNewLabelBytes   = 60
	minimumPiLabelWords      = 3
	maximumPiLabelWords      = 4
	maximumPiExecution       = 15 * time.Second
	maximumPiPipeCleanupTime = 100 * time.Millisecond
	piJSONShortEscapeBytes   = 2
	piJSONCodeUnitBytes      = 4
	piJSONUnicodeEscapeBytes = 6
	piJSONSurrogatePairBytes = 12
	piHexLetterOffset        = 10
	piHexBase                = 16
	piTextSpaceClass         = `\s\p{Z}\x{FEFF}`
)

var (
	piMarkdownFencePattern = regexp.MustCompile(
		"(?m)^[" + piTextSpaceClass + "]{0,3}(?:`{3,}|~{3,})",
	)
	piMarkdownInlineCodePattern = regexp.MustCompile("`[^`\\n]+`")
	piMarkdownBlockStartPattern = regexp.MustCompile(
		`(?m)^[` + piTextSpaceClass + `]{0,3}(?:#{1,6}(?:[ \t]+|$)|[-+*][ \t]+|[0-9]+[.)][ \t]+)`,
	)
	piMarkdownAsteriskPattern = regexp.MustCompile(
		`(?:^|[` + piTextSpaceClass + `(\[{"'])\*{1,3}[^` + piTextSpaceClass +
			`*\n](?:[^*\n]*[^` + piTextSpaceClass + `*\n])?\*{1,3}(?:$|[` + piTextSpaceClass + `)\]},.!?;:'"])`,
	)
	piMarkdownUnderscorePattern = regexp.MustCompile(
		`(?:^|[` + piTextSpaceClass + `(\[{"'])_{1,3}[^` + piTextSpaceClass +
			`_\n](?:[^_\n]*[^` + piTextSpaceClass + `_\n])?_{1,3}(?:$|[` + piTextSpaceClass + `)\]},.!?;:'"])`,
	)
	piMarkdownStrikethroughPattern = regexp.MustCompile(
		`(?:^|[` + piTextSpaceClass + `(\[{"'])~~[^` + piTextSpaceClass +
			`~\n](?:[^~\n]*[^` + piTextSpaceClass + `~\n])?~~(?:$|[` + piTextSpaceClass + `)\]},.!?;:'"])`,
	)
	piMarkdownLinkPattern       = regexp.MustCompile(`\[[^]\n]+\]\([^\n)]*\)`)
	piMarkdownBlockquotePattern = regexp.MustCompile(
		`(?m)^[` + piTextSpaceClass + `]{0,3}>[ \t]?`,
	)
	piMarkdownHorizontalRulePattern = regexp.MustCompile(
		`(?m)^[` + piTextSpaceClass + `]{0,3}(?:(?:\*[ \t]*){3,}|(?:-[ \t]*){3,}|(?:_[ \t]*){3,})$`,
	)
	piMarkdownIndentedCodePattern = regexp.MustCompile(
		`(?m)^(?: {4,}|\t)[^` + piTextSpaceClass + `]`,
	)
	piMarkdownAutolinkPattern = regexp.MustCompile(
		`<(?:[A-Za-z][A-Za-z0-9+.-]{1,31}:[^<>` + piTextSpaceClass +
			`]+|[^<>` + piTextSpaceClass + `@]+@[^<>` + piTextSpaceClass + `@]+\.[^<>` + piTextSpaceClass + `@]+)>`,
	)
)

// ComposeModel identifies the single Pi model requested for composition.
type ComposeModel struct {
	Provider string `json:"provider"`
	ID       string `json:"id"`
	Thinking string `json:"thinking"`
}

// ComposeInput is the latest user and assistant text sent to Pi.
type ComposeInput struct {
	User      string `json:"user"`
	Assistant string `json:"assistant"`
}

// ComposeLabel describes the current label and whether Pi should refresh it.
type ComposeLabel struct {
	Current string `json:"current"`
	Refresh bool   `json:"refresh"`
}

// ComposeResult contains validated plain text generated by Pi. An empty Label
// means the caller should not update its current label.
type ComposeResult struct {
	Body  string `json:"body"`
	Label string `json:"label"`
}

// PiComposer invokes one configured steward Pi helper process per Compose call.
type PiComposer struct {
	Bin   string
	Model ComposeModel
}

type piComposeRequest struct {
	Version   int          `json:"version"`
	Operation string       `json:"operation"`
	Model     ComposeModel `json:"model"`
	Input     ComposeInput `json:"input"`
	Label     ComposeLabel `json:"label"`
}

type piHelperResponse struct {
	result    ComposeResult
	errorCode string
	success   bool
}

type piOutputWriter struct {
	mutex    sync.Mutex
	data     []byte
	overflow bool
	cancel   context.CancelFunc
}

// NewPiComposer resolves the helper and model from the supplied environment.
// Defaults apply only when their corresponding setting is absent.
func NewPiComposer(environ []string) (PiComposer, error) {
	composer := PiComposer{
		Bin: piEnvironmentValue(environ, "STEWARD_HELPER_BIN", defaultPiHelperBin),
		Model: ComposeModel{
			Provider: piEnvironmentValue(environ, "STEWARD_MODEL_PROVIDER", defaultPiModelProvider),
			ID:       piEnvironmentValue(environ, "STEWARD_MODEL_ID", defaultPiModelID),
			Thinking: piEnvironmentValue(environ, "STEWARD_MODEL_THINKING", defaultPiModelThinking),
		},
	}
	if !validPiComposer(composer) {
		return PiComposer{}, piConfigurationError()
	}
	return composer, nil
}

// Compose sends one bounded request to the configured helper and accepts only
// a strict result line whose success state agrees with the process exit status.
func (composer PiComposer) Compose(
	ctx context.Context,
	input ComposeInput,
	label ComposeLabel,
) (ComposeResult, error) {
	if !validPiComposer(composer) {
		return ComposeResult{}, piConfigurationError()
	}
	request, valid := buildPiRequest(composer.Model, input, label)
	if !valid {
		return ComposeResult{}, piRequestError()
	}
	wire, marshalErr := json.Marshal(request)
	if marshalErr != nil || len(wire)+1 > maximumPiWireBytes {
		return ComposeResult{}, piRequestError()
	}
	wire = append(wire, '\n')

	stdout, exitZero, runErr := runPiHelper(ctx, composer.Bin, wire)
	if runErr != nil {
		return ComposeResult{}, runErr
	}
	response, protocolValid := parsePiResponse(stdout, label)
	if !protocolValid || response.success != exitZero {
		return ComposeResult{}, piProtocolError()
	}
	if !response.success {
		return ComposeResult{}, piHelperResponseError(response.errorCode)
	}
	return response.result, nil
}

func piEnvironmentValue(environ []string, name, fallback string) string {
	prefix := name + "="
	value := fallback
	for _, entry := range environ {
		if strings.HasPrefix(entry, prefix) {
			value = strings.TrimPrefix(entry, prefix)
		}
	}
	return value
}

func validPiComposer(composer PiComposer) bool {
	return validPiExecutable(composer.Bin) &&
		validPiModelSetting(composer.Model.Provider) &&
		validPiModelSetting(composer.Model.ID) &&
		validPiThinking(composer.Model.Thinking)
}

func validPiExecutable(value string) bool {
	return value != "" && utf8.ValidString(value) && !containsPiControl(value)
}

func validPiModelSetting(value string) bool {
	return value != "" && len(value) <= maximumPiSettingBytes &&
		utf8.ValidString(value) && !containsPiControl(value)
}

func validPiThinking(value string) bool {
	switch value {
	case "minimal", "low", "medium", "high", "xhigh", "max":
		return true
	default:
		return false
	}
}

func buildPiRequest(model ComposeModel, input ComposeInput, label ComposeLabel) (piComposeRequest, bool) {
	if !utf8.ValidString(input.User) || !utf8.ValidString(input.Assistant) ||
		!utf8.ValidString(label.Current) || len(label.Current) > maximumPiLabelBytes {
		return piComposeRequest{}, false
	}

	userBudget := maximumPiInputBytes - min(len(input.Assistant), reservedPiInputBytes)
	assistantBudget := maximumPiInputBytes - min(len(input.User), reservedPiInputBytes)
	request := piComposeRequest{
		Version:   1,
		Operation: "compose",
		Model:     model,
		Input: ComposeInput{
			User:      piUTF8Tail(input.User, userBudget),
			Assistant: piUTF8Tail(input.Assistant, assistantBudget),
		},
		Label: label,
	}
	return request, true
}

func piUTF8Tail(value string, budget int) string {
	if len(value) <= budget {
		return value
	}
	start := len(value) - budget
	for start < len(value) && !utf8.RuneStart(value[start]) {
		start++
	}
	return value[start:]
}

func runPiHelper(ctx context.Context, bin string, wire []byte) ([]byte, bool, error) {
	runCtx, cancel := context.WithTimeout(ctx, maximumPiExecution)
	defer cancel()
	if runCtx.Err() != nil {
		return nil, false, piContextError(runCtx.Err())
	}

	path, lookupErr := exec.LookPath(bin)
	if lookupErr != nil {
		return nil, false, piHelperUnavailableError()
	}
	stdout := &piOutputWriter{data: make([]byte, 0, maximumPiOutputBytes), cancel: cancel}
	cmd := &exec.Cmd{
		Path:      path,
		Args:      []string{bin},
		Stdin:     bytes.NewReader(wire),
		Stdout:    stdout,
		Stderr:    io.Discard,
		WaitDelay: maximumPiPipeCleanupTime,
	}
	if runCtx.Err() != nil {
		return nil, false, piContextError(runCtx.Err())
	}
	if startErr := cmd.Start(); startErr != nil {
		return nil, false, piHelperExecutionError()
	}
	runErr := waitPiHelper(runCtx, cmd)
	output, overflow := stdout.snapshot()
	if overflow {
		return nil, false, piProtocolError()
	}
	if runCtx.Err() != nil {
		return nil, false, piContextError(runCtx.Err())
	}
	if runErr == nil {
		return output, true, nil
	}
	var exitErr *exec.ExitError
	if errors.As(runErr, &exitErr) {
		return output, false, nil
	}
	return nil, false, piHelperExecutionError()
}

func waitPiHelper(ctx context.Context, cmd *exec.Cmd) error {
	waited := make(chan error, 1)
	go func() {
		waited <- cmd.Wait()
	}()
	select {
	case waitErr := <-waited:
		return waitErr
	case <-ctx.Done():
		killErr := cmd.Process.Kill()
		waitErr := <-waited
		return errors.Join(ctx.Err(), killErr, waitErr)
	}
}

func (writer *piOutputWriter) Write(data []byte) (int, error) {
	writer.mutex.Lock()
	remaining := maximumPiOutputBytes - len(writer.data)
	if remaining > 0 {
		writer.data = append(writer.data, data[:min(len(data), remaining)]...)
	}
	if len(data) > remaining {
		writer.overflow = true
		writer.cancel()
	}
	writer.mutex.Unlock()
	return len(data), nil
}

func (writer *piOutputWriter) snapshot() ([]byte, bool) {
	writer.mutex.Lock()
	defer writer.mutex.Unlock()
	return bytes.Clone(writer.data), writer.overflow
}

func parsePiResponse(stdout []byte, label ComposeLabel) (piHelperResponse, bool) {
	if len(stdout) == 0 || len(stdout) > maximumPiOutputBytes || !utf8.Valid(stdout) ||
		stdout[len(stdout)-1] != '\n' || bytes.Count(stdout, []byte{'\n'}) != 1 {
		return piHelperResponse{}, false
	}
	fields, valid := strictPiObject(stdout[:len(stdout)-1])
	if !valid {
		return piHelperResponse{}, false
	}
	var version int
	var ok bool
	if !decodePiField(fields, "version", &version) || version != 1 || !decodePiField(fields, "ok", &ok) {
		return piHelperResponse{}, false
	}
	if ok {
		return parsePiSuccess(fields, label)
	}
	return parsePiFailure(fields)
}

func strictPiObject(raw []byte) (map[string]json.RawMessage, bool) {
	decoder := json.NewDecoder(bytes.NewReader(raw))
	opening, err := decoder.Token()
	if err != nil || opening != json.Delim('{') {
		return nil, false
	}
	fields := make(map[string]json.RawMessage)
	for decoder.More() {
		keyToken, keyErr := decoder.Token()
		key, keyOK := keyToken.(string)
		if keyErr != nil || !keyOK {
			return nil, false
		}
		if _, duplicate := fields[key]; duplicate {
			return nil, false
		}
		var value json.RawMessage
		if decodeErr := decoder.Decode(&value); decodeErr != nil {
			return nil, false
		}
		fields[key] = value
	}
	closing, closeErr := decoder.Token()
	if closeErr != nil || closing != json.Delim('}') {
		return nil, false
	}
	var trailing json.RawMessage
	if trailingErr := decoder.Decode(&trailing); !errors.Is(trailingErr, io.EOF) {
		return nil, false
	}
	return fields, true
}

func decodePiField(fields map[string]json.RawMessage, name string, destination any) bool {
	raw, present := fields[name]
	if !present || bytes.Equal(bytes.TrimSpace(raw), []byte("null")) {
		return false
	}
	return json.Unmarshal(raw, destination) == nil
}

func decodePiStringField(fields map[string]json.RawMessage, name string, destination *string) bool {
	raw, present := fields[name]
	if !present || !validPiJSONString(raw) {
		return false
	}
	return json.Unmarshal(raw, destination) == nil
}

func validPiJSONString(raw json.RawMessage) bool {
	if len(raw) < 2 || raw[0] != '"' || raw[len(raw)-1] != '"' {
		return false
	}
	for index := 1; index < len(raw)-1; {
		if raw[index] != '\\' {
			index++
			continue
		}
		consumed, valid := validPiJSONEscape(raw[index : len(raw)-1])
		if !valid {
			return false
		}
		index += consumed
	}
	return true
}

func validPiJSONEscape(raw []byte) (int, bool) {
	if len(raw) < piJSONShortEscapeBytes || raw[1] != 'u' {
		return min(len(raw), piJSONShortEscapeBytes), true
	}
	if len(raw) < piJSONUnicodeEscapeBytes {
		return 0, false
	}
	unit, valid := piHexCodeUnit(raw[2:])
	if !valid || unit >= 0xdc00 && unit <= 0xdfff {
		return 0, false
	}
	if unit < 0xd800 || unit > 0xdbff {
		return piJSONUnicodeEscapeBytes, true
	}
	if len(raw) < piJSONSurrogatePairBytes || raw[6] != '\\' || raw[7] != 'u' {
		return 0, false
	}
	low, lowValid := piHexCodeUnit(raw[8:])
	return piJSONSurrogatePairBytes, lowValid && low >= 0xdc00 && low <= 0xdfff
}

func piHexCodeUnit(raw []byte) (uint16, bool) {
	if len(raw) < piJSONCodeUnitBytes {
		return 0, false
	}
	var result uint16
	for _, digit := range raw[:piJSONCodeUnitBytes] {
		value, valid := piHexDigit(digit)
		if !valid {
			return 0, false
		}
		result = result*piHexBase + value
	}
	return result, true
}

func piHexDigit(digit byte) (uint16, bool) {
	switch {
	case digit >= '0' && digit <= '9':
		return uint16(digit - '0'), true
	case digit >= 'a' && digit <= 'f':
		return uint16(digit-'a') + piHexLetterOffset, true
	case digit >= 'A' && digit <= 'F':
		return uint16(digit-'A') + piHexLetterOffset, true
	default:
		return 0, false
	}
}

func parsePiSuccess(fields map[string]json.RawMessage, label ComposeLabel) (piHelperResponse, bool) {
	hasLabel, validShape := validPiSuccessShape(fields, label)
	if !validShape {
		return piHelperResponse{}, false
	}

	var body string
	if !decodePiStringField(fields, "body", &body) || !validPiBody(body) {
		return piHelperResponse{}, false
	}
	result := ComposeResult{Body: body}
	if hasLabel && (!decodePiStringField(fields, "label", &result.Label) || !validPiGeneratedLabel(result.Label)) {
		return piHelperResponse{}, false
	}
	return piHelperResponse{result: result, success: true}, true
}

func validPiSuccessShape(fields map[string]json.RawMessage, label ComposeLabel) (bool, bool) {
	_, hasLabel := fields["label"]
	switch {
	case !label.Refresh:
		return hasLabel, exactPiFields(fields, "version", "ok", "body")
	case hasLabel:
		return true, exactPiFields(fields, "version", "ok", "body", "label")
	default:
		return false, label.Current != "" && exactPiFields(fields, "version", "ok", "body")
	}
}

func parsePiFailure(fields map[string]json.RawMessage) (piHelperResponse, bool) {
	if !exactPiFields(fields, "version", "ok", "error") {
		return piHelperResponse{}, false
	}
	var code string
	if !decodePiStringField(fields, "error", &code) {
		return piHelperResponse{}, false
	}
	switch code {
	case "invalid_request", "unavailable_model", "generation_failed", "timeout", "invalid_output":
		return piHelperResponse{errorCode: code}, true
	default:
		return piHelperResponse{}, false
	}
}

func exactPiFields(fields map[string]json.RawMessage, names ...string) bool {
	if len(fields) != len(names) {
		return false
	}
	for _, name := range names {
		if _, present := fields[name]; !present {
			return false
		}
	}
	return true
}

func validPiBody(value string) bool {
	return strings.TrimFunc(value, isPiWhitespace) != "" &&
		utf8.RuneCountInString(value) <= maximumPiBodyCodepoints && validPiPlainText(value)
}

func validPiGeneratedLabel(value string) bool {
	words := strings.FieldsFunc(value, isPiWhitespace)
	return strings.TrimFunc(value, isPiWhitespace) != "" && len(value) <= maximumPiNewLabelBytes &&
		len(words) >= minimumPiLabelWords && len(words) <= maximumPiLabelWords && validPiPlainText(value)
}

func validPiPlainText(value string) bool {
	return utf8.ValidString(value) && !containsPiControl(value) && !containsPiBidiControl(value) &&
		!piMarkdownFencePattern.MatchString(value) &&
		!piMarkdownInlineCodePattern.MatchString(value) &&
		!piMarkdownBlockStartPattern.MatchString(value) &&
		!piMarkdownAsteriskPattern.MatchString(value) &&
		!piMarkdownUnderscorePattern.MatchString(value) &&
		!piMarkdownStrikethroughPattern.MatchString(value) &&
		!piMarkdownLinkPattern.MatchString(value) &&
		!piMarkdownBlockquotePattern.MatchString(value) &&
		!piMarkdownHorizontalRulePattern.MatchString(value) &&
		!piMarkdownIndentedCodePattern.MatchString(value) &&
		!piMarkdownAutolinkPattern.MatchString(value)
}

func isPiWhitespace(character rune) bool {
	return unicode.IsSpace(character) || character == '\ufeff'
}

func containsPiControl(value string) bool {
	for _, character := range value {
		if character <= '\u001f' || (character >= '\u007f' && character <= '\u009f') {
			return true
		}
	}
	return false
}

func containsPiBidiControl(value string) bool {
	for _, character := range value {
		if character == '\u061c' || character == '\u200e' || character == '\u200f' ||
			(character >= '\u202a' && character <= '\u202e') ||
			(character >= '\u2066' && character <= '\u2069') {
			return true
		}
	}
	return false
}

func piConfigurationError() error {
	return errors.New("pi composer: invalid configuration")
}

func piRequestError() error {
	return errors.New("pi composer: invalid compose request")
}

func piHelperUnavailableError() error {
	return errors.New("pi composer: helper unavailable")
}

func piHelperExecutionError() error {
	return errors.New("pi composer: helper execution failed")
}

func piContextError(err error) error {
	if errors.Is(err, context.DeadlineExceeded) {
		return errors.New("pi composer: helper timed out")
	}
	return errors.New("pi composer: helper canceled")
}

func piProtocolError() error {
	return errors.New("pi composer: invalid helper protocol")
}

func piHelperResponseError(code string) error {
	switch code {
	case "invalid_request":
		return errors.New("pi composer: helper rejected request")
	case "unavailable_model":
		return errors.New("pi composer: helper model unavailable")
	case "generation_failed":
		return errors.New("pi composer: helper generation failed")
	case "timeout":
		return errors.New("pi composer: helper reported timeout")
	case "invalid_output":
		return errors.New("pi composer: helper output invalid")
	default:
		return piProtocolError()
	}
}
